"""Constants file for """

GEOMETRY = 'GEOMETRY'

INPUT_SIZE = 'INPUT_SIZE'
OPTIM_SIZE = 'OPTIM_SIZE'
AXIS = 'AXIS'

THETA_START = 'THETA_START'
THETA_STOP = 'THETA_STOP'
THETA_STEP = 'THETA_STEP'

OPTIMIZATION = 'OPTIMIZATION'

SPLINE_ORDER = 'SPLINE_ORDER'
SIGMA = 'SIGMA'

NF = 'NF'

WF_LR = 'WF_LR'
INR_LR = 'INR_LR'

WF_START_ITER = 'WF_START_ITER'
WF_ITERS_PER_RESOLUTION = 'WF_ITERS_PER_RESOLUTION'
WF_SIZES = 'WF_SIZES'

NUM_FRAMES = 'NUM_FRAMES'

NORMALIZE_SINO = 'NORMALIZE_SINO'

SAVE_ITERS = 'SAVE_ITERS'

INPUT_SINO = 'INPUT_SINO'

SAVE_DIR = 'SAVE_DIR'

SAVE_OPTIONS = 'SAVE_OPTIONS'

TRANS = 'TRANS'
